#!/usr/bin/env bash
# The resolved palette for scripts: `palette light.background "#FFFFFF"` prints
# the role from shared/build/generated/poster/palette.properties (generated by
# ./gradlew :shared:generatePosterConfig from poster.properties), or the
# fallback when the file is missing. Source this file; do not run it.
POSTER_PALETTE_FILE="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)/shared/build/generated/poster/palette.properties"
palette() {
  local value
  value=$(grep "^$1=" "$POSTER_PALETTE_FILE" 2>/dev/null | head -1 | cut -d= -f2)
  printf '%s' "${value:-$2}"
}
palette_ensure() {
  [ -f "$POSTER_PALETTE_FILE" ] && return 0
  (cd "$(dirname "$POSTER_PALETTE_FILE")/../../.." && ./gradlew :shared:generatePosterConfig -q --no-daemon) || true
}
